import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Suspense } from "react";
import dynamic from 'next/dynamic';
import { SpeedInsights } from "@vercel/speed-insights/next"

const Loading = dynamic(() => import('./loading'), {
  suspense: true,
});

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Line Clone App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body>
        <Suspense fallback={<Loading />}>{children}</Suspense>
        <SpeedInsights />
      </body>
    </html>
  );
}
